name: Python App Workflow

on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message with Real Time
        run: |
          echo "Hello from GitHub Actions! The time is $(date '+%Y-%m-%d %H:%M:%S.%N')"
